### ISSUE TITLE
ExternalDocumentRef with non sha1 checksums do not validate correctly

### ISSUE THREAD

**Issue by puerco** [spdx/spdx-java-tagvalue-store#14]
When validating a spdx Tag/Value doc with an `ExternalDocumentRef` using a checksum with an algorithm different than sha1, `Verify` will complain that the reference is invalid even when it is well formed and [it is a valid checksum algorithm](https://spdx.github.io/spdx-spec/4-file-information/#44-file-checksum).

Example using ext reference 
`DocumentRef-kubernetes-v1.22.0-beta.1 https://k8s.io/sbom/source/v1.22.0-beta.1 SHA256: 9b01bf4e25f170cba6b8ad1db4297d2d4b7ddebbebf87cc440a1a6f537f48637`

```
java -jar tmp/tools-java-1.0.1-jar-with-dependencies.jar Verify tmp/kubernetes-release.spdx 
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
Analysis exception processing SPDX file: Invalid external document reference: DocumentRef-kubernetes-v1.22.0-beta.1 https://k8s.io/sbom/source/v1.22.0-beta.1 SHA256: 9b01bf4e25f170cba6b8ad1db4297d2d4b7ddebbebf87cc440a1a6f537f48637 at line number 6
```

If I change the external reference to SHA1, using the following tag it works:
`ExternalDocumentRef:DocumentRef-kubernetes-v1.22.0-beta.1 https://k8s.io/sbom/source/v1.22.0-beta.1 SHA1: 89b0b411c5381564689f5ce96a84b2987d25acfa`

```
java -jar tmp/tools-java-1.0.1-jar-with-dependencies.jar Verify tmp/kubernetes-release.spdx 
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
This SPDX Document is valid.
```

I also tested with sha512 and it also did not work.

**Comment by goneall** [comment]
Resolved with PR #15
