### ISSUE TITLE
Incorrect conversion for FileCopyrightText

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-java-tagvalue-store#23]
I have a tag-value SPDX file that contains:
```
PackageCopyrightText: NOASSERTION
```
for one package and
```
PackageCopyrightText: NONE
```
for another.

After converting the file to JSON then to tag-value, I get the following:
```
PackageCopyrightText: <text>NOASSERTION</text>
```
and
```
PackageCopyrightText: <text>NONE</text>
```

**Comment by vargenau** [comment]
I still see the issue in the online tool.
Probably the new code has not been deployed.

**Comment by goneall** [comment]
This should have been deployed - I'll re-open this issue and see if I can find out what happened.

**Comment by goneall** [comment]
@vargenau I just tried this out on the online tools and it seems to work.

Attached is an archive with 3 files I used in the test:
- SPDXTagExample-v2.3.spdx - the input file with a PackageCopyrightText of NOASSERTION
- test.json - intermediate JSON test file converted from the SPDXTagExample-v2.3.spdx file
- output.spdx - final output file from converting test.json to tag/value

The output.spdx file seems to have the correct value.

If you have a test file that duplicates the issue, please upload and I'll look into it further
[test-files.zip](https://github.com/spdx/spdx-java-tagvalue-store/files/9378155/test-files.zip)
.

**Comment by goneall** [comment]
@vargenau You can also check the version of the online tools in the about tab at the bottom of the page.  It should read:

```
Spdx online tools version : 1.0.7
Java Tools version : 1.1.0
```

**Comment by vargenau** [comment]
@goneall 
Conversion is done at https://tools.spdx.org/app/convert/

I have:
Spdx online tools version : 1.0.7
Java Tools version : 1.1.0

File is taken from https://github.com/spdx/spdx-examples.git in example3/spdx

[example3-src.spdx.txt](example3-src.spdx.txt)
[example3-src.spdx.json.txt](example3-src.spdx.json.txt)
[example3-src-from-json.spdx.txt](example3-src-from-json.spdx.txt)

**Comment by goneall** [comment]
Thanks @vargenau for the additional info.

I now see the issue.  I fixed the packageCopyrightText, but the fileCopyrightText is still an issue.

If you agree, I'll rename this issue and resolve it in a future release.

**Comment by vargenau** [comment]
@goneall
That is fine for me.
