### ISSUE TITLE
SPDX Tag-Value validator: Unexpected Error: org.spdx.library.model.SpdxIdInUseException: Can not create Apache-2.0. It is already in use with type ListedLicense which is incompatible with type ExtractedLicensingInfo

### ISSUE THREAD

**Issue by kzantow** [spdx/spdx-java-tagvalue-store#31]
While attempting to validate the attached SPDX Tag-Value file, it results in this error in the online validator:

```
Analysis exception processing SPDX file: Unexpected Error: org.spdx.library.model.SpdxIdInUseException: 
Can not create Apache-2.0. It is already in use with type ListedLicense which is incompatible with type 
ExtractedLicensingInfo
```

This is difficult to understand what the problem is -- is it a parser issue or something wrong with the SPDX file?

[sample.spdx.txt](https://github.com/spdx/spdx-online-tools/files/10180438/sample.spdx.txt)

**Comment by kzantow** [comment]
Thank you very much for the response @goneall -- I've had a hard time finding information about the overall Tag Value format (I see plenty of individual property examples in the SPDX docs, but nothing describing the actual TV format itself). Is there any way you could point me to some documentation for this?

**Comment by goneall** [comment]
@kzantow aside from [the spec itself](https://spdx.github.io/spdx-spec/v2.3/), there is a [repo of examples](https://github.com/spdx/spdx-examples) which may be helpful.
