### ISSUE TITLE
Converting from JSON to tag:value creates invalid SPDX

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-java-tagvalue-store#58]
[bug.spdx.json.txt](https://github.com/spdx/tools-java/files/13964713/bug.spdx.json.txt)

[bug.spdx.txt](https://github.com/spdx/tools-java/files/13964708/bug.spdx.txt)

We have a valid SPDX JSON file `bug.spdx.json`.

With `tools-java` we convert it to tag:value giving `bug.spdx`.

`bug.spdx` is invalid accoding to `tools-python`:
```
pyspdxtools -i bug.spdx
ERROR:root:There have been issues while parsing the provided document:
Element Package is not the current element in scope, probably the expected tag to start the element (PackageName) is missing. Line: 32
```

tools-java release 1.1.8

**Comment by goneall** [comment]
Note that section 5.2.2 of the SPDX 2.3 spec states:

```
Annotations and relationships for the package may appear after the package information before any file information.
```

It doesn't use the word "shall", but this could be interpreted as a required ordering.

In either case, this is fixed with PR #59
