### ISSUE TITLE
Parsing PrimaryPackagePurpose of OPERATING-SYSTEM fails

### ISSUE THREAD

**Issue by medcrypt-matt** [spdx/spdx-java-tagvalue-store#61]
If a SPDX 2.3 tag/value file contains `PrimaryPackagePurpose: OPERATING-SYSTEM` then attempts to convert the file, or to deserialize it using `SpdxToolsHelper.deserializeDocument` will fail with `org.spdx.tag.InvalidSpdxTagFileException: Unknown Package Purpose: OPERATING-SYSTEM`

This value is perfectly valid according to the spec: 
https://spdx.github.io/spdx-spec/v2.3/package-information/#724-primary-package-purpose-field

The problem seems to be that the enum member is named OPERATING_SYSTEM (note the underscore)

**Comment by goneall** [comment]
Thanks @medcrypt-matt for reporting this.  This should be a straightforward fix, but it may be a while before I get to it myself.  If you want to create a PR, I can review / merge otherwise I'll take a look once I finish the 3.0 upgrades to the library.
